// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: grpc/dssa.proto

package dssagrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_grpc_dssa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{0}
}

func (x *Path) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DataEntries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DataEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntries) Reset() {
	*x = DataEntries{}
	mi := &file_grpc_dssa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntries) ProtoMessage() {}

func (x *DataEntries) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntries.ProtoReflect.Descriptor instead.
func (*DataEntries) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{1}
}

func (x *DataEntries) GetEntries() []*DataEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntry) Reset() {
	*x = DataEntry{}
	mi := &file_grpc_dssa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntry) ProtoMessage() {}

func (x *DataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntry.ProtoReflect.Descriptor instead.
func (*DataEntry) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{2}
}

func (x *DataEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

var File_grpc_dssa_proto protoreflect.FileDescriptor

const file_grpc_dssa_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpc/dssa.proto\x12\x04dssa\"\x1a\n" +
	"\x04Path\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"8\n" +
	"\vDataEntries\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.dssa.DataEntryR\aentries\"6\n" +
	"\tDataEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir2<\n" +
	"\x11DataStorageSystem\x12'\n" +
	"\x04List\x12\n" +
	".dssa.Path\x1a\x11.dssa.DataEntries\"\x00B\fZ\n" +
	"./dssagrpcb\x06proto3"

var (
	file_grpc_dssa_proto_rawDescOnce sync.Once
	file_grpc_dssa_proto_rawDescData []byte
)

func file_grpc_dssa_proto_rawDescGZIP() []byte {
	file_grpc_dssa_proto_rawDescOnce.Do(func() {
		file_grpc_dssa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_dssa_proto_rawDesc), len(file_grpc_dssa_proto_rawDesc)))
	})
	return file_grpc_dssa_proto_rawDescData
}

var file_grpc_dssa_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_dssa_proto_goTypes = []any{
	(*Path)(nil),        // 0: dssa.Path
	(*DataEntries)(nil), // 1: dssa.DataEntries
	(*DataEntry)(nil),   // 2: dssa.DataEntry
}
var file_grpc_dssa_proto_depIdxs = []int32{
	2, // 0: dssa.DataEntries.entries:type_name -> dssa.DataEntry
	0, // 1: dssa.DataStorageSystem.List:input_type -> dssa.Path
	1, // 2: dssa.DataStorageSystem.List:output_type -> dssa.DataEntries
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_dssa_proto_init() }
func file_grpc_dssa_proto_init() {
	if File_grpc_dssa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_dssa_proto_rawDesc), len(file_grpc_dssa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_dssa_proto_goTypes,
		DependencyIndexes: file_grpc_dssa_proto_depIdxs,
		MessageInfos:      file_grpc_dssa_proto_msgTypes,
	}.Build()
	File_grpc_dssa_proto = out.File
	file_grpc_dssa_proto_goTypes = nil
	file_grpc_dssa_proto_depIdxs = nil
}
