// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: grpc/dssa.proto

package dssagrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_grpc_dssa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{0}
}

func (x *Path) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OldNewPaths struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Old           string                 `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New_          string                 `protobuf:"bytes,2,opt,name=new_,json=new,proto3" json:"new_,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OldNewPaths) Reset() {
	*x = OldNewPaths{}
	mi := &file_grpc_dssa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OldNewPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OldNewPaths) ProtoMessage() {}

func (x *OldNewPaths) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OldNewPaths.ProtoReflect.Descriptor instead.
func (*OldNewPaths) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{1}
}

func (x *OldNewPaths) GetOld() string {
	if x != nil {
		return x.Old
	}
	return ""
}

func (x *OldNewPaths) GetNew_() string {
	if x != nil {
		return x.New_
	}
	return ""
}

type DataEntries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DataEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntries) Reset() {
	*x = DataEntries{}
	mi := &file_grpc_dssa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntries) ProtoMessage() {}

func (x *DataEntries) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntries.ProtoReflect.Descriptor instead.
func (*DataEntries) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{2}
}

func (x *DataEntries) GetEntries() []*DataEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDir         bool                   `protobuf:"varint,1,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                  `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	User          int32                  `protobuf:"varint,5,opt,name=user,proto3" json:"user,omitempty"`
	UserRights    *Rights                `protobuf:"bytes,6,opt,name=user_rights,json=userRights,proto3" json:"user_rights,omitempty"`
	Group         int32                  `protobuf:"varint,7,opt,name=group,proto3" json:"group,omitempty"`
	GroupRights   *Rights                `protobuf:"bytes,8,opt,name=group_rights,json=groupRights,proto3" json:"group_rights,omitempty"`
	OtherRights   *Rights                `protobuf:"bytes,9,opt,name=other_rights,json=otherRights,proto3" json:"other_rights,omitempty"`
	IsSymLink     bool                   `protobuf:"varint,10,opt,name=is_sym_link,json=isSymLink,proto3" json:"is_sym_link,omitempty"`
	SymLinkTarget string                 `protobuf:"bytes,11,opt,name=sym_link_target,json=symLinkTarget,proto3" json:"sym_link_target,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	ErrNotExist   bool                   `protobuf:"varint,13,opt,name=err_not_exist,json=errNotExist,proto3" json:"err_not_exist,omitempty"`
	Id            string                 `protobuf:"bytes,14,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntry) Reset() {
	*x = DataEntry{}
	mi := &file_grpc_dssa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntry) ProtoMessage() {}

func (x *DataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntry.ProtoReflect.Descriptor instead.
func (*DataEntry) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{3}
}

func (x *DataEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DataEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DataEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DataEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *DataEntry) GetUser() int32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *DataEntry) GetUserRights() *Rights {
	if x != nil {
		return x.UserRights
	}
	return nil
}

func (x *DataEntry) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *DataEntry) GetGroupRights() *Rights {
	if x != nil {
		return x.GroupRights
	}
	return nil
}

func (x *DataEntry) GetOtherRights() *Rights {
	if x != nil {
		return x.OtherRights
	}
	return nil
}

func (x *DataEntry) GetIsSymLink() bool {
	if x != nil {
		return x.IsSymLink
	}
	return false
}

func (x *DataEntry) GetSymLinkTarget() string {
	if x != nil {
		return x.SymLinkTarget
	}
	return ""
}

func (x *DataEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DataEntry) GetErrNotExist() bool {
	if x != nil {
		return x.ErrNotExist
	}
	return false
}

func (x *DataEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetStatDataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataEntry     *DataEntry             `protobuf:"bytes,1,opt,name=data_entry,json=dataEntry,proto3" json:"data_entry,omitempty"`
	NoPerm        bool                   `protobuf:"varint,2,opt,name=no_perm,json=noPerm,proto3" json:"no_perm,omitempty"`
	NoMtime       bool                   `protobuf:"varint,3,opt,name=no_mtime,json=noMtime,proto3" json:"no_mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatDataEntry) Reset() {
	*x = SetStatDataEntry{}
	mi := &file_grpc_dssa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatDataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatDataEntry) ProtoMessage() {}

func (x *SetStatDataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatDataEntry.ProtoReflect.Descriptor instead.
func (*SetStatDataEntry) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{4}
}

func (x *SetStatDataEntry) GetDataEntry() *DataEntry {
	if x != nil {
		return x.DataEntry
	}
	return nil
}

func (x *SetStatDataEntry) GetNoPerm() bool {
	if x != nil {
		return x.NoPerm
	}
	return false
}

func (x *SetStatDataEntry) GetNoMtime() bool {
	if x != nil {
		return x.NoMtime
	}
	return false
}

type Rights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          bool                   `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write         bool                   `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	Execute       bool                   `protobuf:"varint,3,opt,name=execute,proto3" json:"execute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rights) Reset() {
	*x = Rights{}
	mi := &file_grpc_dssa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rights) ProtoMessage() {}

func (x *Rights) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rights.ProtoReflect.Descriptor instead.
func (*Rights) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{5}
}

func (x *Rights) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Rights) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

func (x *Rights) GetExecute() bool {
	if x != nil {
		return x.Execute
	}
	return false
}

type PushedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushedBlock) Reset() {
	*x = PushedBlock{}
	mi := &file_grpc_dssa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushedBlock) ProtoMessage() {}

func (x *PushedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushedBlock.ProtoReflect.Descriptor instead.
func (*PushedBlock) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{6}
}

func (x *PushedBlock) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushedBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PulledBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulledBlock) Reset() {
	*x = PulledBlock{}
	mi := &file_grpc_dssa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulledBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulledBlock) ProtoMessage() {}

func (x *PulledBlock) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulledBlock.ProtoReflect.Descriptor instead.
func (*PulledBlock) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{7}
}

func (x *PulledBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Length struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int64                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Length) Reset() {
	*x = Length{}
	mi := &file_grpc_dssa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Length) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Length) ProtoMessage() {}

func (x *Length) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Length.ProtoReflect.Descriptor instead.
func (*Length) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{8}
}

func (x *Length) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_dssa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_dssa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_dssa_proto_rawDescGZIP(), []int{9}
}

var File_grpc_dssa_proto protoreflect.FileDescriptor

const file_grpc_dssa_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpc/dssa.proto\x12\x04dssa\"\x1a\n" +
	"\x04Path\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"2\n" +
	"\vOldNewPaths\x12\x10\n" +
	"\x03old\x18\x01 \x01(\tR\x03old\x12\x11\n" +
	"\x04new_\x18\x02 \x01(\tR\x03new\"8\n" +
	"\vDataEntries\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.dssa.DataEntryR\aentries\"\xad\x03\n" +
	"\tDataEntry\x12\x15\n" +
	"\x06is_dir\x18\x01 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04user\x18\x05 \x01(\x05R\x04user\x12-\n" +
	"\vuser_rights\x18\x06 \x01(\v2\f.dssa.RightsR\n" +
	"userRights\x12\x14\n" +
	"\x05group\x18\a \x01(\x05R\x05group\x12/\n" +
	"\fgroup_rights\x18\b \x01(\v2\f.dssa.RightsR\vgroupRights\x12/\n" +
	"\fother_rights\x18\t \x01(\v2\f.dssa.RightsR\votherRights\x12\x1e\n" +
	"\vis_sym_link\x18\n" +
	" \x01(\bR\tisSymLink\x12&\n" +
	"\x0fsym_link_target\x18\v \x01(\tR\rsymLinkTarget\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12\"\n" +
	"\rerr_not_exist\x18\r \x01(\bR\verrNotExist\x12\x0e\n" +
	"\x02id\x18\x0e \x01(\tR\x02id\"v\n" +
	"\x10SetStatDataEntry\x12.\n" +
	"\n" +
	"data_entry\x18\x01 \x01(\v2\x0f.dssa.DataEntryR\tdataEntry\x12\x17\n" +
	"\ano_perm\x18\x02 \x01(\bR\x06noPerm\x12\x19\n" +
	"\bno_mtime\x18\x03 \x01(\bR\anoMtime\"L\n" +
	"\x06Rights\x12\x12\n" +
	"\x04read\x18\x01 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x02 \x01(\bR\x05write\x12\x18\n" +
	"\aexecute\x18\x03 \x01(\bR\aexecute\"5\n" +
	"\vPushedBlock\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"!\n" +
	"\vPulledBlock\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\" \n" +
	"\x06Length\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x03R\x06length\"\a\n" +
	"\x05Empty2\xe2\x02\n" +
	"\x11DataStorageSystem\x12'\n" +
	"\x04List\x12\n" +
	".dssa.Path\x1a\x11.dssa.DataEntries\"\x00\x12%\n" +
	"\x04Stat\x12\n" +
	".dssa.Path\x1a\x0f.dssa.DataEntry\"\x00\x12'\n" +
	"\x05Mkdir\x12\x0f.dssa.DataEntry\x1a\v.dssa.Empty\"\x00\x120\n" +
	"\aSetStat\x12\x16.dssa.SetStatDataEntry\x1a\v.dssa.Empty\"\x00\x12*\n" +
	"\x03Put\x12\x11.dssa.PushedBlock\x1a\f.dssa.Length\"\x00(\x01\x12(\n" +
	"\x03Get\x12\n" +
	".dssa.Path\x1a\x11.dssa.PulledBlock\"\x000\x01\x12\x1f\n" +
	"\x02Rm\x12\n" +
	".dssa.Path\x1a\v.dssa.Empty\"\x00\x12+\n" +
	"\aSymlink\x12\x11.dssa.OldNewPaths\x1a\v.dssa.Empty\"\x00B\fZ\n" +
	"./dssagrpcb\x06proto3"

var (
	file_grpc_dssa_proto_rawDescOnce sync.Once
	file_grpc_dssa_proto_rawDescData []byte
)

func file_grpc_dssa_proto_rawDescGZIP() []byte {
	file_grpc_dssa_proto_rawDescOnce.Do(func() {
		file_grpc_dssa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_dssa_proto_rawDesc), len(file_grpc_dssa_proto_rawDesc)))
	})
	return file_grpc_dssa_proto_rawDescData
}

var file_grpc_dssa_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_grpc_dssa_proto_goTypes = []any{
	(*Path)(nil),             // 0: dssa.Path
	(*OldNewPaths)(nil),      // 1: dssa.OldNewPaths
	(*DataEntries)(nil),      // 2: dssa.DataEntries
	(*DataEntry)(nil),        // 3: dssa.DataEntry
	(*SetStatDataEntry)(nil), // 4: dssa.SetStatDataEntry
	(*Rights)(nil),           // 5: dssa.Rights
	(*PushedBlock)(nil),      // 6: dssa.PushedBlock
	(*PulledBlock)(nil),      // 7: dssa.PulledBlock
	(*Length)(nil),           // 8: dssa.Length
	(*Empty)(nil),            // 9: dssa.Empty
}
var file_grpc_dssa_proto_depIdxs = []int32{
	3,  // 0: dssa.DataEntries.entries:type_name -> dssa.DataEntry
	5,  // 1: dssa.DataEntry.user_rights:type_name -> dssa.Rights
	5,  // 2: dssa.DataEntry.group_rights:type_name -> dssa.Rights
	5,  // 3: dssa.DataEntry.other_rights:type_name -> dssa.Rights
	3,  // 4: dssa.SetStatDataEntry.data_entry:type_name -> dssa.DataEntry
	0,  // 5: dssa.DataStorageSystem.List:input_type -> dssa.Path
	0,  // 6: dssa.DataStorageSystem.Stat:input_type -> dssa.Path
	3,  // 7: dssa.DataStorageSystem.Mkdir:input_type -> dssa.DataEntry
	4,  // 8: dssa.DataStorageSystem.SetStat:input_type -> dssa.SetStatDataEntry
	6,  // 9: dssa.DataStorageSystem.Put:input_type -> dssa.PushedBlock
	0,  // 10: dssa.DataStorageSystem.Get:input_type -> dssa.Path
	0,  // 11: dssa.DataStorageSystem.Rm:input_type -> dssa.Path
	1,  // 12: dssa.DataStorageSystem.Symlink:input_type -> dssa.OldNewPaths
	2,  // 13: dssa.DataStorageSystem.List:output_type -> dssa.DataEntries
	3,  // 14: dssa.DataStorageSystem.Stat:output_type -> dssa.DataEntry
	9,  // 15: dssa.DataStorageSystem.Mkdir:output_type -> dssa.Empty
	9,  // 16: dssa.DataStorageSystem.SetStat:output_type -> dssa.Empty
	8,  // 17: dssa.DataStorageSystem.Put:output_type -> dssa.Length
	7,  // 18: dssa.DataStorageSystem.Get:output_type -> dssa.PulledBlock
	9,  // 19: dssa.DataStorageSystem.Rm:output_type -> dssa.Empty
	9,  // 20: dssa.DataStorageSystem.Symlink:output_type -> dssa.Empty
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_grpc_dssa_proto_init() }
func file_grpc_dssa_proto_init() {
	if File_grpc_dssa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_dssa_proto_rawDesc), len(file_grpc_dssa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_dssa_proto_goTypes,
		DependencyIndexes: file_grpc_dssa_proto_depIdxs,
		MessageInfos:      file_grpc_dssa_proto_msgTypes,
	}.Build()
	File_grpc_dssa_proto = out.File
	file_grpc_dssa_proto_goTypes = nil
	file_grpc_dssa_proto_depIdxs = nil
}
