// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: grpc/dssa.proto

package dssagrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataStorageSystem_List_FullMethodName    = "/dssa.DataStorageSystem/List"
	DataStorageSystem_Stat_FullMethodName    = "/dssa.DataStorageSystem/Stat"
	DataStorageSystem_SetStat_FullMethodName = "/dssa.DataStorageSystem/SetStat"
	DataStorageSystem_Put_FullMethodName     = "/dssa.DataStorageSystem/Put"
	DataStorageSystem_Get_FullMethodName     = "/dssa.DataStorageSystem/Get"
)

// DataStorageSystemClient is the client API for DataStorageSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataStorageSystemClient interface {
	List(ctx context.Context, in *Path, opts ...grpc.CallOption) (*DataEntries, error)
	Stat(ctx context.Context, in *Path, opts ...grpc.CallOption) (*DataEntry, error)
	SetStat(ctx context.Context, in *DataEntry, opts ...grpc.CallOption) (*Empty, error)
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushedBlock, Length], error)
	Get(ctx context.Context, in *Path, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PulledBlock], error)
}

type dataStorageSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewDataStorageSystemClient(cc grpc.ClientConnInterface) DataStorageSystemClient {
	return &dataStorageSystemClient{cc}
}

func (c *dataStorageSystemClient) List(ctx context.Context, in *Path, opts ...grpc.CallOption) (*DataEntries, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataEntries)
	err := c.cc.Invoke(ctx, DataStorageSystem_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStorageSystemClient) Stat(ctx context.Context, in *Path, opts ...grpc.CallOption) (*DataEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataEntry)
	err := c.cc.Invoke(ctx, DataStorageSystem_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStorageSystemClient) SetStat(ctx context.Context, in *DataEntry, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DataStorageSystem_SetStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStorageSystemClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushedBlock, Length], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataStorageSystem_ServiceDesc.Streams[0], DataStorageSystem_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushedBlock, Length]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageSystem_PutClient = grpc.ClientStreamingClient[PushedBlock, Length]

func (c *dataStorageSystemClient) Get(ctx context.Context, in *Path, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PulledBlock], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataStorageSystem_ServiceDesc.Streams[1], DataStorageSystem_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Path, PulledBlock]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageSystem_GetClient = grpc.ServerStreamingClient[PulledBlock]

// DataStorageSystemServer is the server API for DataStorageSystem service.
// All implementations must embed UnimplementedDataStorageSystemServer
// for forward compatibility.
type DataStorageSystemServer interface {
	List(context.Context, *Path) (*DataEntries, error)
	Stat(context.Context, *Path) (*DataEntry, error)
	SetStat(context.Context, *DataEntry) (*Empty, error)
	Put(grpc.ClientStreamingServer[PushedBlock, Length]) error
	Get(*Path, grpc.ServerStreamingServer[PulledBlock]) error
	mustEmbedUnimplementedDataStorageSystemServer()
}

// UnimplementedDataStorageSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataStorageSystemServer struct{}

func (UnimplementedDataStorageSystemServer) List(context.Context, *Path) (*DataEntries, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDataStorageSystemServer) Stat(context.Context, *Path) (*DataEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedDataStorageSystemServer) SetStat(context.Context, *DataEntry) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStat not implemented")
}
func (UnimplementedDataStorageSystemServer) Put(grpc.ClientStreamingServer[PushedBlock, Length]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedDataStorageSystemServer) Get(*Path, grpc.ServerStreamingServer[PulledBlock]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDataStorageSystemServer) mustEmbedUnimplementedDataStorageSystemServer() {}
func (UnimplementedDataStorageSystemServer) testEmbeddedByValue()                           {}

// UnsafeDataStorageSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataStorageSystemServer will
// result in compilation errors.
type UnsafeDataStorageSystemServer interface {
	mustEmbedUnimplementedDataStorageSystemServer()
}

func RegisterDataStorageSystemServer(s grpc.ServiceRegistrar, srv DataStorageSystemServer) {
	// If the following call panics, it indicates UnimplementedDataStorageSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataStorageSystem_ServiceDesc, srv)
}

func _DataStorageSystem_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Path)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageSystemServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageSystem_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageSystemServer).List(ctx, req.(*Path))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStorageSystem_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Path)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageSystemServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageSystem_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageSystemServer).Stat(ctx, req.(*Path))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStorageSystem_SetStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageSystemServer).SetStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageSystem_SetStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageSystemServer).SetStat(ctx, req.(*DataEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStorageSystem_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataStorageSystemServer).Put(&grpc.GenericServerStream[PushedBlock, Length]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageSystem_PutServer = grpc.ClientStreamingServer[PushedBlock, Length]

func _DataStorageSystem_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Path)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataStorageSystemServer).Get(m, &grpc.GenericServerStream[Path, PulledBlock]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageSystem_GetServer = grpc.ServerStreamingServer[PulledBlock]

// DataStorageSystem_ServiceDesc is the grpc.ServiceDesc for DataStorageSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataStorageSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dssa.DataStorageSystem",
	HandlerType: (*DataStorageSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DataStorageSystem_List_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _DataStorageSystem_Stat_Handler,
		},
		{
			MethodName: "SetStat",
			Handler:    _DataStorageSystem_SetStat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _DataStorageSystem_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _DataStorageSystem_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/dssa.proto",
}
