// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: grpc/ope.proto

package opegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ope_Ready_FullMethodName    = "/ope.Ope/Ready"
	Ope_Version_FullMethodName  = "/ope.Ope/Version"
	Ope_Shutdown_FullMethodName = "/ope.Ope/Shutdown"
)

// OpeClient is the client API for Ope service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpeClient interface {
	Ready(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Bool, error)
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Value, error)
	Shutdown(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Bool, error)
}

type opeClient struct {
	cc grpc.ClientConnInterface
}

func NewOpeClient(cc grpc.ClientConnInterface) OpeClient {
	return &opeClient{cc}
}

func (c *opeClient) Ready(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bool)
	err := c.cc.Invoke(ctx, Ope_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opeClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Value)
	err := c.cc.Invoke(ctx, Ope_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opeClient) Shutdown(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bool)
	err := c.cc.Invoke(ctx, Ope_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpeServer is the server API for Ope service.
// All implementations must embed UnimplementedOpeServer
// for forward compatibility.
type OpeServer interface {
	Ready(context.Context, *Empty) (*Bool, error)
	Version(context.Context, *Empty) (*Value, error)
	Shutdown(context.Context, *Value) (*Bool, error)
	mustEmbedUnimplementedOpeServer()
}

// UnimplementedOpeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpeServer struct{}

func (UnimplementedOpeServer) Ready(context.Context, *Empty) (*Bool, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedOpeServer) Version(context.Context, *Empty) (*Value, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedOpeServer) Shutdown(context.Context, *Value) (*Bool, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedOpeServer) mustEmbedUnimplementedOpeServer() {}
func (UnimplementedOpeServer) testEmbeddedByValue()             {}

// UnsafeOpeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpeServer will
// result in compilation errors.
type UnsafeOpeServer interface {
	mustEmbedUnimplementedOpeServer()
}

func RegisterOpeServer(s grpc.ServiceRegistrar, srv OpeServer) {
	// If the following call panics, it indicates UnimplementedOpeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ope_ServiceDesc, srv)
}

func _Ope_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpeServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ope_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpeServer).Ready(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ope_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpeServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ope_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpeServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ope_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ope_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpeServer).Shutdown(ctx, req.(*Value))
	}
	return interceptor(ctx, in, info, handler)
}

// Ope_ServiceDesc is the grpc.ServiceDesc for Ope service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ope_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ope.Ope",
	HandlerType: (*OpeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ready",
			Handler:    _Ope_Ready_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Ope_Version_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Ope_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/ope.proto",
}
