syntax = "proto3";

package opelog;

option go_package = "./opeloggrpc";

message Rights {
    bool read = 1;
    bool write = 2;
    bool execute = 3;
}

message StoredEntry {
    bool is_dir = 1;
    int64 size = 2;
    int64 mtime = 3;
    int32 user = 4;
    Rights user_rights = 5;
    int32 group = 6;
    Rights group_rights = 7;
    Rights other_rights = 8;
    bool is_sym_link = 9;
    string sym_link_target = 10;
    repeated string children = 11;
    bytes add_meta = 12;
}

enum HalgoCode {
    HAL_UNSPECIFIED = 0;
    HAL_MD5 = 1;
    HAL_SHA256 = 2;
    HAL_SHA512 = 3;
    HAL_SHA3_256 = 4;
    HAL_SHA3_512 = 5;
}

message TypedChecksum {
    // first byte is HalgoCode, checksum comes after
    bytes tcs = 1;
}

enum EventCode {
   EVC_UNSPECIFIED = 0;
   EVC_LOADED = 1;
   EVC_REMOVED = 2;
   EVC_CREATED = 3;
   EVC_UPDATED = 4;
   EVC_META_CHANGED = 5;
}

message Event {
    EventCode kind = 1;
    int64 session_time = 2;
    int64 time_stamp = 3;
    // negative number means no entry
    sint32 se_num = 4;
    repeated sint32 tcs_nums = 5;
    string error = 6;
}

message AggInfo {
    int64 number = 1;
    int64 size = 2;
}

message ComputedStats {
    int64 time_stamp = 1;
    // list for dirs, stats for others, performed both on source and target
    AggInfo source_list_or_stat = 2;
    AggInfo target_list_or_stat = 3;
    // other I/Os specific to source or to target
    AggInfo read = 4;
    AggInfo create = 5;
    AggInfo update = 6;
    AggInfo remove = 7;
    AggInfo meta_change = 8;
    AggInfo error = 9;
}

enum StateCode {
   STC_UNSPECIFIED = 0;
   STC_DONE_ABSENT = 1;
   STC_DONE_PRESENT = 2;
   STC_DIR_LOAD = 3;
   STC_DIR_RM = 4;
   STC_DIR_CHANGE = 5;
   STC_SE_ERROR = 6;
   STC_CHILD_ERROR = 7;
}

message LogicalEntry {
    // Checksums and stored entries are shared and referenced by index
    repeated StoredEntry shared_ses = 1;
    repeated TypedChecksum shared_tcss = 2;
    map<int64,StateCode> source_states = 3;
    repeated Event source_events = 5;
    map<int64,StateCode> target_states = 6;
    repeated Event target_events = 7;
    repeated ComputedStats stats_list = 9;
    // if current_session changed, on-going 
    int64 last_session
    int32 source_dep_count
    int32 target_dep_count
}

// For a memory to file simple implementation, limited to 2GiB, cf https://protobuf.dev/programming-guides/proto-limits/#total
message OpeLogAllInOne {
    string source_root = 1;
    string target_root = 2;
    // the key is the relative path
    map<string,LogicalEntry> logical_entries = 3;
    // the key is the session label the value is its start time
    map<string,int64> sessions = 4;
}