syntax = "proto3";

package opelog;

option go_package = "./opeloggrpc";

message LogEntry {
    string rel_path = 1;
    repeated OpeLogEntry ope_log_entries = 2;
}

message StoredEntry {
    int64 size = 1;
    int64 mtime = 2;
    uint32 uid = 3;
    uint32 gid = 4;
    uint32 mode = 5;
    string sym_link_target = 6;
}

message Checksums {
    // comma-separated list algo:hexa-of-checksum
    string checksums = 1;
}

enum OpeCode {
   OPE_CODE_UNSPECIFIED = 0;
   OPE_CODE_SOURCE_STAT = 1;
   OPE_CODE_TARGET_STAT = 2;
   OPE_CODE_SOURCE_CHECKSUM = 3;
   OPE_CODE_TARGET_CHECKSUM = 4;
   OPE_CODE_MKDIR = 5;
   OPE_CODE_COPY = 6;
   OPE_CODE_SYMLINK = 7;
   OPE_CODE_DELETE = 8;
   OPE_CODE_SET_STAT = 9;
}

message OpeLogEntry {
    OpeCode code = 1;
    bool check = 2;
    int64 time_stamp = 3;
    uint64 error_id = 4;
    StoredEntry source = 5;
    StoredEntry target = 6;
}

// For a memory to file simple implementation, limited to 2GiB, cf https://protobuf.dev/programming-guides/proto-limits/#total
message OpeLogAllInOne {
    string source = 1;
    string target = 2;
    repeated LogEntry log_entries = 3;
}