// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: grpc/opelog.proto

package opeloggrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventCode int32

const (
	EventCode_EVT_UNSPECIFIED EventCode = 0
	EventCode_EVT_ABS         EventCode = 1
	EventCode_EVT_EXIST       EventCode = 2
	EventCode_EVT_CR_MOD      EventCode = 3
	EventCode_EVT_ATTS_CHG    EventCode = 4
	EventCode_EVT_START_DIRUP EventCode = 5
	EventCode_EVT_END_DIRUP   EventCode = 6
)

// Enum value maps for EventCode.
var (
	EventCode_name = map[int32]string{
		0: "EVT_UNSPECIFIED",
		1: "EVT_ABS",
		2: "EVT_EXIST",
		3: "EVT_CR_MOD",
		4: "EVT_ATTS_CHG",
		5: "EVT_START_DIRUP",
		6: "EVT_END_DIRUP",
	}
	EventCode_value = map[string]int32{
		"EVT_UNSPECIFIED": 0,
		"EVT_ABS":         1,
		"EVT_EXIST":       2,
		"EVT_CR_MOD":      3,
		"EVT_ATTS_CHG":    4,
		"EVT_START_DIRUP": 5,
		"EVT_END_DIRUP":   6,
	}
)

func (x EventCode) Enum() *EventCode {
	p := new(EventCode)
	*p = x
	return p
}

func (x EventCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_opelog_proto_enumTypes[0].Descriptor()
}

func (EventCode) Type() protoreflect.EnumType {
	return &file_grpc_opelog_proto_enumTypes[0]
}

func (x EventCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventCode.Descriptor instead.
func (EventCode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{0}
}

type OriginCode int32

const (
	OriginCode_ORI_UNSPECIFIED OriginCode = 0
	OriginCode_ORI_LIST        OriginCode = 1
	OriginCode_ORI_STAT        OriginCode = 2
	OriginCode_ORI_READ        OriginCode = 3
	OriginCode_ORI_MKDIR       OriginCode = 4
	OriginCode_ORI_WRITE       OriginCode = 5
	OriginCode_ORI_SET_STAT    OriginCode = 6
	OriginCode_ORI_RM          OriginCode = 7
)

// Enum value maps for OriginCode.
var (
	OriginCode_name = map[int32]string{
		0: "ORI_UNSPECIFIED",
		1: "ORI_LIST",
		2: "ORI_STAT",
		3: "ORI_READ",
		4: "ORI_MKDIR",
		5: "ORI_WRITE",
		6: "ORI_SET_STAT",
		7: "ORI_RM",
	}
	OriginCode_value = map[string]int32{
		"ORI_UNSPECIFIED": 0,
		"ORI_LIST":        1,
		"ORI_STAT":        2,
		"ORI_READ":        3,
		"ORI_MKDIR":       4,
		"ORI_WRITE":       5,
		"ORI_SET_STAT":    6,
		"ORI_RM":          7,
	}
)

func (x OriginCode) Enum() *OriginCode {
	p := new(OriginCode)
	*p = x
	return p
}

func (x OriginCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OriginCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_opelog_proto_enumTypes[1].Descriptor()
}

func (OriginCode) Type() protoreflect.EnumType {
	return &file_grpc_opelog_proto_enumTypes[1]
}

func (x OriginCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OriginCode.Descriptor instead.
func (OriginCode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{1}
}

type Rights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          bool                   `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write         bool                   `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	Execute       bool                   `protobuf:"varint,3,opt,name=execute,proto3" json:"execute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rights) Reset() {
	*x = Rights{}
	mi := &file_grpc_opelog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rights) ProtoMessage() {}

func (x *Rights) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rights.ProtoReflect.Descriptor instead.
func (*Rights) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{0}
}

func (x *Rights) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Rights) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

func (x *Rights) GetExecute() bool {
	if x != nil {
		return x.Execute
	}
	return false
}

type StoredEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPresent     bool                   `protobuf:"varint,1,opt,name=is_present,json=isPresent,proto3" json:"is_present,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                  `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	User          int32                  `protobuf:"varint,5,opt,name=user,proto3" json:"user,omitempty"`
	UserRights    *Rights                `protobuf:"bytes,6,opt,name=user_rights,json=userRights,proto3" json:"user_rights,omitempty"`
	Group         int32                  `protobuf:"varint,7,opt,name=group,proto3" json:"group,omitempty"`
	GroupRights   *Rights                `protobuf:"bytes,8,opt,name=group_rights,json=groupRights,proto3" json:"group_rights,omitempty"`
	OtherRights   *Rights                `protobuf:"bytes,9,opt,name=other_rights,json=otherRights,proto3" json:"other_rights,omitempty"`
	IsSymLink     bool                   `protobuf:"varint,10,opt,name=is_sym_link,json=isSymLink,proto3" json:"is_sym_link,omitempty"`
	SymLinkTarget string                 `protobuf:"bytes,11,opt,name=sym_link_target,json=symLinkTarget,proto3" json:"sym_link_target,omitempty"`
	Children      []string               `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredEntry) Reset() {
	*x = StoredEntry{}
	mi := &file_grpc_opelog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredEntry) ProtoMessage() {}

func (x *StoredEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredEntry.ProtoReflect.Descriptor instead.
func (*StoredEntry) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{1}
}

func (x *StoredEntry) GetIsPresent() bool {
	if x != nil {
		return x.IsPresent
	}
	return false
}

func (x *StoredEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StoredEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StoredEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *StoredEntry) GetUser() int32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *StoredEntry) GetUserRights() *Rights {
	if x != nil {
		return x.UserRights
	}
	return nil
}

func (x *StoredEntry) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *StoredEntry) GetGroupRights() *Rights {
	if x != nil {
		return x.GroupRights
	}
	return nil
}

func (x *StoredEntry) GetOtherRights() *Rights {
	if x != nil {
		return x.OtherRights
	}
	return nil
}

func (x *StoredEntry) GetIsSymLink() bool {
	if x != nil {
		return x.IsSymLink
	}
	return false
}

func (x *StoredEntry) GetSymLinkTarget() string {
	if x != nil {
		return x.SymLinkTarget
	}
	return ""
}

func (x *StoredEntry) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventCode              `protobuf:"varint,1,opt,name=kind,proto3,enum=opelog.EventCode" json:"kind,omitempty"`
	Origin        OriginCode             `protobuf:"varint,2,opt,name=origin,proto3,enum=opelog.OriginCode" json:"origin,omitempty"`
	UpdateCount   int32                  `protobuf:"varint,3,opt,name=update_count,json=updateCount,proto3" json:"update_count,omitempty"`
	ValidateCount int32                  `protobuf:"varint,4,opt,name=validate_count,json=validateCount,proto3" json:"validate_count,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,5,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	StateIndex    int32                  `protobuf:"varint,6,opt,name=state_index,json=stateIndex,proto3" json:"state_index,omitempty"`
	// comma-separated list algo:hexa-of-checksum
	Checksums     string `protobuf:"bytes,7,opt,name=checksums,proto3" json:"checksums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_grpc_opelog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetKind() EventCode {
	if x != nil {
		return x.Kind
	}
	return EventCode_EVT_UNSPECIFIED
}

func (x *Event) GetOrigin() OriginCode {
	if x != nil {
		return x.Origin
	}
	return OriginCode_ORI_UNSPECIFIED
}

func (x *Event) GetUpdateCount() int32 {
	if x != nil {
		return x.UpdateCount
	}
	return 0
}

func (x *Event) GetValidateCount() int32 {
	if x != nil {
		return x.ValidateCount
	}
	return 0
}

func (x *Event) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *Event) GetStateIndex() int32 {
	if x != nil {
		return x.StateIndex
	}
	return 0
}

func (x *Event) GetChecksums() string {
	if x != nil {
		return x.Checksums
	}
	return ""
}

type AggInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggInfo) Reset() {
	*x = AggInfo{}
	mi := &file_grpc_opelog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggInfo) ProtoMessage() {}

func (x *AggInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggInfo.ProtoReflect.Descriptor instead.
func (*AggInfo) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{3}
}

func (x *AggInfo) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *AggInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ComputedStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimeStamp        int64                  `protobuf:"varint,1,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	SourceListOrStat *AggInfo               `protobuf:"bytes,2,opt,name=source_list_or_stat,json=sourceListOrStat,proto3" json:"source_list_or_stat,omitempty"`
	TargetListOrStat *AggInfo               `protobuf:"bytes,3,opt,name=target_list_or_stat,json=targetListOrStat,proto3" json:"target_list_or_stat,omitempty"`
	Read             *AggInfo               `protobuf:"bytes,4,opt,name=read,proto3" json:"read,omitempty"`
	Create           *AggInfo               `protobuf:"bytes,5,opt,name=create,proto3" json:"create,omitempty"`
	Update           *AggInfo               `protobuf:"bytes,6,opt,name=update,proto3" json:"update,omitempty"`
	Remove           *AggInfo               `protobuf:"bytes,7,opt,name=remove,proto3" json:"remove,omitempty"`
	ModChange        *AggInfo               `protobuf:"bytes,8,opt,name=mod_change,json=modChange,proto3" json:"mod_change,omitempty"`
	Error            *AggInfo               `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComputedStats) Reset() {
	*x = ComputedStats{}
	mi := &file_grpc_opelog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputedStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputedStats) ProtoMessage() {}

func (x *ComputedStats) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputedStats.ProtoReflect.Descriptor instead.
func (*ComputedStats) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{4}
}

func (x *ComputedStats) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *ComputedStats) GetSourceListOrStat() *AggInfo {
	if x != nil {
		return x.SourceListOrStat
	}
	return nil
}

func (x *ComputedStats) GetTargetListOrStat() *AggInfo {
	if x != nil {
		return x.TargetListOrStat
	}
	return nil
}

func (x *ComputedStats) GetRead() *AggInfo {
	if x != nil {
		return x.Read
	}
	return nil
}

func (x *ComputedStats) GetCreate() *AggInfo {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *ComputedStats) GetUpdate() *AggInfo {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ComputedStats) GetRemove() *AggInfo {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *ComputedStats) GetModChange() *AggInfo {
	if x != nil {
		return x.ModChange
	}
	return nil
}

func (x *ComputedStats) GetError() *AggInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type LogicalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keeping source and target states out of event saves storage when unchanged
	SourceStates        []*StoredEntry   `protobuf:"bytes,1,rep,name=source_states,json=sourceStates,proto3" json:"source_states,omitempty"`
	SourceEvents        []*Event         `protobuf:"bytes,2,rep,name=source_events,json=sourceEvents,proto3" json:"source_events,omitempty"`
	TargetStates        []*StoredEntry   `protobuf:"bytes,3,rep,name=target_states,json=targetStates,proto3" json:"target_states,omitempty"`
	TransientDirupState *StoredEntry     `protobuf:"bytes,4,opt,name=transient_dirup_state,json=transientDirupState,proto3" json:"transient_dirup_state,omitempty"`
	TargetEvents        []*Event         `protobuf:"bytes,5,rep,name=target_events,json=targetEvents,proto3" json:"target_events,omitempty"`
	StatsList           []*ComputedStats `protobuf:"bytes,6,rep,name=stats_list,json=statsList,proto3" json:"stats_list,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LogicalEntry) Reset() {
	*x = LogicalEntry{}
	mi := &file_grpc_opelog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalEntry) ProtoMessage() {}

func (x *LogicalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalEntry.ProtoReflect.Descriptor instead.
func (*LogicalEntry) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{5}
}

func (x *LogicalEntry) GetSourceStates() []*StoredEntry {
	if x != nil {
		return x.SourceStates
	}
	return nil
}

func (x *LogicalEntry) GetSourceEvents() []*Event {
	if x != nil {
		return x.SourceEvents
	}
	return nil
}

func (x *LogicalEntry) GetTargetStates() []*StoredEntry {
	if x != nil {
		return x.TargetStates
	}
	return nil
}

func (x *LogicalEntry) GetTransientDirupState() *StoredEntry {
	if x != nil {
		return x.TransientDirupState
	}
	return nil
}

func (x *LogicalEntry) GetTargetEvents() []*Event {
	if x != nil {
		return x.TargetEvents
	}
	return nil
}

func (x *LogicalEntry) GetStatsList() []*ComputedStats {
	if x != nil {
		return x.StatsList
	}
	return nil
}

// For a memory to file simple implementation, limited to 2GiB, cf https://protobuf.dev/programming-guides/proto-limits/#total
type OpeLogAllInOne struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceRoot string                 `protobuf:"bytes,1,opt,name=source_root,json=sourceRoot,proto3" json:"source_root,omitempty"`
	TargetRoot string                 `protobuf:"bytes,2,opt,name=target_root,json=targetRoot,proto3" json:"target_root,omitempty"`
	// the key is the relative path
	LogicalEntries map[string]*LogicalEntry `protobuf:"bytes,3,rep,name=logical_entries,json=logicalEntries,proto3" json:"logical_entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpeLogAllInOne) Reset() {
	*x = OpeLogAllInOne{}
	mi := &file_grpc_opelog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeLogAllInOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeLogAllInOne) ProtoMessage() {}

func (x *OpeLogAllInOne) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeLogAllInOne.ProtoReflect.Descriptor instead.
func (*OpeLogAllInOne) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{6}
}

func (x *OpeLogAllInOne) GetSourceRoot() string {
	if x != nil {
		return x.SourceRoot
	}
	return ""
}

func (x *OpeLogAllInOne) GetTargetRoot() string {
	if x != nil {
		return x.TargetRoot
	}
	return ""
}

func (x *OpeLogAllInOne) GetLogicalEntries() map[string]*LogicalEntry {
	if x != nil {
		return x.LogicalEntries
	}
	return nil
}

var File_grpc_opelog_proto protoreflect.FileDescriptor

const file_grpc_opelog_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/opelog.proto\x12\x06opelog\"L\n" +
	"\x06Rights\x12\x12\n" +
	"\x04read\x18\x01 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x02 \x01(\bR\x05write\x12\x18\n" +
	"\aexecute\x18\x03 \x01(\bR\aexecute\"\x92\x03\n" +
	"\vStoredEntry\x12\x1d\n" +
	"\n" +
	"is_present\x18\x01 \x01(\bR\tisPresent\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04user\x18\x05 \x01(\x05R\x04user\x12/\n" +
	"\vuser_rights\x18\x06 \x01(\v2\x0e.opelog.RightsR\n" +
	"userRights\x12\x14\n" +
	"\x05group\x18\a \x01(\x05R\x05group\x121\n" +
	"\fgroup_rights\x18\b \x01(\v2\x0e.opelog.RightsR\vgroupRights\x121\n" +
	"\fother_rights\x18\t \x01(\v2\x0e.opelog.RightsR\votherRights\x12\x1e\n" +
	"\vis_sym_link\x18\n" +
	" \x01(\bR\tisSymLink\x12&\n" +
	"\x0fsym_link_target\x18\v \x01(\tR\rsymLinkTarget\x12\x1a\n" +
	"\bchildren\x18\f \x03(\tR\bchildren\"\x82\x02\n" +
	"\x05Event\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.opelog.EventCodeR\x04kind\x12*\n" +
	"\x06origin\x18\x02 \x01(\x0e2\x12.opelog.OriginCodeR\x06origin\x12!\n" +
	"\fupdate_count\x18\x03 \x01(\x05R\vupdateCount\x12%\n" +
	"\x0evalidate_count\x18\x04 \x01(\x05R\rvalidateCount\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x05 \x01(\x03R\ttimeStamp\x12\x1f\n" +
	"\vstate_index\x18\x06 \x01(\x05R\n" +
	"stateIndex\x12\x1c\n" +
	"\tchecksums\x18\a \x01(\tR\tchecksums\"5\n" +
	"\aAggInfo\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\xa5\x03\n" +
	"\rComputedStats\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x01 \x01(\x03R\ttimeStamp\x12>\n" +
	"\x13source_list_or_stat\x18\x02 \x01(\v2\x0f.opelog.AggInfoR\x10sourceListOrStat\x12>\n" +
	"\x13target_list_or_stat\x18\x03 \x01(\v2\x0f.opelog.AggInfoR\x10targetListOrStat\x12#\n" +
	"\x04read\x18\x04 \x01(\v2\x0f.opelog.AggInfoR\x04read\x12'\n" +
	"\x06create\x18\x05 \x01(\v2\x0f.opelog.AggInfoR\x06create\x12'\n" +
	"\x06update\x18\x06 \x01(\v2\x0f.opelog.AggInfoR\x06update\x12'\n" +
	"\x06remove\x18\a \x01(\v2\x0f.opelog.AggInfoR\x06remove\x12.\n" +
	"\n" +
	"mod_change\x18\b \x01(\v2\x0f.opelog.AggInfoR\tmodChange\x12%\n" +
	"\x05error\x18\t \x01(\v2\x0f.opelog.AggInfoR\x05error\"\xe9\x02\n" +
	"\fLogicalEntry\x128\n" +
	"\rsource_states\x18\x01 \x03(\v2\x13.opelog.StoredEntryR\fsourceStates\x122\n" +
	"\rsource_events\x18\x02 \x03(\v2\r.opelog.EventR\fsourceEvents\x128\n" +
	"\rtarget_states\x18\x03 \x03(\v2\x13.opelog.StoredEntryR\ftargetStates\x12G\n" +
	"\x15transient_dirup_state\x18\x04 \x01(\v2\x13.opelog.StoredEntryR\x13transientDirupState\x122\n" +
	"\rtarget_events\x18\x05 \x03(\v2\r.opelog.EventR\ftargetEvents\x124\n" +
	"\n" +
	"stats_list\x18\x06 \x03(\v2\x15.opelog.ComputedStatsR\tstatsList\"\x80\x02\n" +
	"\x0eOpeLogAllInOne\x12\x1f\n" +
	"\vsource_root\x18\x01 \x01(\tR\n" +
	"sourceRoot\x12\x1f\n" +
	"\vtarget_root\x18\x02 \x01(\tR\n" +
	"targetRoot\x12S\n" +
	"\x0flogical_entries\x18\x03 \x03(\v2*.opelog.OpeLogAllInOne.LogicalEntriesEntryR\x0elogicalEntries\x1aW\n" +
	"\x13LogicalEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.opelog.LogicalEntryR\x05value:\x028\x01*\x86\x01\n" +
	"\tEventCode\x12\x13\n" +
	"\x0fEVT_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aEVT_ABS\x10\x01\x12\r\n" +
	"\tEVT_EXIST\x10\x02\x12\x0e\n" +
	"\n" +
	"EVT_CR_MOD\x10\x03\x12\x10\n" +
	"\fEVT_ATTS_CHG\x10\x04\x12\x13\n" +
	"\x0fEVT_START_DIRUP\x10\x05\x12\x11\n" +
	"\rEVT_END_DIRUP\x10\x06*\x87\x01\n" +
	"\n" +
	"OriginCode\x12\x13\n" +
	"\x0fORI_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bORI_LIST\x10\x01\x12\f\n" +
	"\bORI_STAT\x10\x02\x12\f\n" +
	"\bORI_READ\x10\x03\x12\r\n" +
	"\tORI_MKDIR\x10\x04\x12\r\n" +
	"\tORI_WRITE\x10\x05\x12\x10\n" +
	"\fORI_SET_STAT\x10\x06\x12\n" +
	"\n" +
	"\x06ORI_RM\x10\aB\x0eZ\f./opeloggrpcb\x06proto3"

var (
	file_grpc_opelog_proto_rawDescOnce sync.Once
	file_grpc_opelog_proto_rawDescData []byte
)

func file_grpc_opelog_proto_rawDescGZIP() []byte {
	file_grpc_opelog_proto_rawDescOnce.Do(func() {
		file_grpc_opelog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_opelog_proto_rawDesc), len(file_grpc_opelog_proto_rawDesc)))
	})
	return file_grpc_opelog_proto_rawDescData
}

var file_grpc_opelog_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_opelog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_opelog_proto_goTypes = []any{
	(EventCode)(0),         // 0: opelog.EventCode
	(OriginCode)(0),        // 1: opelog.OriginCode
	(*Rights)(nil),         // 2: opelog.Rights
	(*StoredEntry)(nil),    // 3: opelog.StoredEntry
	(*Event)(nil),          // 4: opelog.Event
	(*AggInfo)(nil),        // 5: opelog.AggInfo
	(*ComputedStats)(nil),  // 6: opelog.ComputedStats
	(*LogicalEntry)(nil),   // 7: opelog.LogicalEntry
	(*OpeLogAllInOne)(nil), // 8: opelog.OpeLogAllInOne
	nil,                    // 9: opelog.OpeLogAllInOne.LogicalEntriesEntry
}
var file_grpc_opelog_proto_depIdxs = []int32{
	2,  // 0: opelog.StoredEntry.user_rights:type_name -> opelog.Rights
	2,  // 1: opelog.StoredEntry.group_rights:type_name -> opelog.Rights
	2,  // 2: opelog.StoredEntry.other_rights:type_name -> opelog.Rights
	0,  // 3: opelog.Event.kind:type_name -> opelog.EventCode
	1,  // 4: opelog.Event.origin:type_name -> opelog.OriginCode
	5,  // 5: opelog.ComputedStats.source_list_or_stat:type_name -> opelog.AggInfo
	5,  // 6: opelog.ComputedStats.target_list_or_stat:type_name -> opelog.AggInfo
	5,  // 7: opelog.ComputedStats.read:type_name -> opelog.AggInfo
	5,  // 8: opelog.ComputedStats.create:type_name -> opelog.AggInfo
	5,  // 9: opelog.ComputedStats.update:type_name -> opelog.AggInfo
	5,  // 10: opelog.ComputedStats.remove:type_name -> opelog.AggInfo
	5,  // 11: opelog.ComputedStats.mod_change:type_name -> opelog.AggInfo
	5,  // 12: opelog.ComputedStats.error:type_name -> opelog.AggInfo
	3,  // 13: opelog.LogicalEntry.source_states:type_name -> opelog.StoredEntry
	4,  // 14: opelog.LogicalEntry.source_events:type_name -> opelog.Event
	3,  // 15: opelog.LogicalEntry.target_states:type_name -> opelog.StoredEntry
	3,  // 16: opelog.LogicalEntry.transient_dirup_state:type_name -> opelog.StoredEntry
	4,  // 17: opelog.LogicalEntry.target_events:type_name -> opelog.Event
	6,  // 18: opelog.LogicalEntry.stats_list:type_name -> opelog.ComputedStats
	9,  // 19: opelog.OpeLogAllInOne.logical_entries:type_name -> opelog.OpeLogAllInOne.LogicalEntriesEntry
	7,  // 20: opelog.OpeLogAllInOne.LogicalEntriesEntry.value:type_name -> opelog.LogicalEntry
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_grpc_opelog_proto_init() }
func file_grpc_opelog_proto_init() {
	if File_grpc_opelog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_opelog_proto_rawDesc), len(file_grpc_opelog_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_opelog_proto_goTypes,
		DependencyIndexes: file_grpc_opelog_proto_depIdxs,
		EnumInfos:         file_grpc_opelog_proto_enumTypes,
		MessageInfos:      file_grpc_opelog_proto_msgTypes,
	}.Build()
	File_grpc_opelog_proto = out.File
	file_grpc_opelog_proto_goTypes = nil
	file_grpc_opelog_proto_depIdxs = nil
}
