// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: grpc/opelog.proto

package opeloggrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpeCode int32

const (
	OpeCode_OPE_CODE_UNSPECIFIED     OpeCode = 0
	OpeCode_OPE_CODE_SOURCE_STAT     OpeCode = 1
	OpeCode_OPE_CODE_TARGET_STAT     OpeCode = 2
	OpeCode_OPE_CODE_SOURCE_CHECKSUM OpeCode = 3
	OpeCode_OPE_CODE_TARGET_CHECKSUM OpeCode = 4
	OpeCode_OPE_CODE_MKDIR           OpeCode = 5
	OpeCode_OPE_CODE_COPY            OpeCode = 6
	OpeCode_OPE_CODE_SYMLINK         OpeCode = 7
	OpeCode_OPE_CODE_DELETE          OpeCode = 8
	OpeCode_OPE_CODE_SET_STAT        OpeCode = 9
)

// Enum value maps for OpeCode.
var (
	OpeCode_name = map[int32]string{
		0: "OPE_CODE_UNSPECIFIED",
		1: "OPE_CODE_SOURCE_STAT",
		2: "OPE_CODE_TARGET_STAT",
		3: "OPE_CODE_SOURCE_CHECKSUM",
		4: "OPE_CODE_TARGET_CHECKSUM",
		5: "OPE_CODE_MKDIR",
		6: "OPE_CODE_COPY",
		7: "OPE_CODE_SYMLINK",
		8: "OPE_CODE_DELETE",
		9: "OPE_CODE_SET_STAT",
	}
	OpeCode_value = map[string]int32{
		"OPE_CODE_UNSPECIFIED":     0,
		"OPE_CODE_SOURCE_STAT":     1,
		"OPE_CODE_TARGET_STAT":     2,
		"OPE_CODE_SOURCE_CHECKSUM": 3,
		"OPE_CODE_TARGET_CHECKSUM": 4,
		"OPE_CODE_MKDIR":           5,
		"OPE_CODE_COPY":            6,
		"OPE_CODE_SYMLINK":         7,
		"OPE_CODE_DELETE":          8,
		"OPE_CODE_SET_STAT":        9,
	}
)

func (x OpeCode) Enum() *OpeCode {
	p := new(OpeCode)
	*p = x
	return p
}

func (x OpeCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpeCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_opelog_proto_enumTypes[0].Descriptor()
}

func (OpeCode) Type() protoreflect.EnumType {
	return &file_grpc_opelog_proto_enumTypes[0]
}

func (x OpeCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpeCode.Descriptor instead.
func (OpeCode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelPath       string                 `protobuf:"bytes,1,opt,name=rel_path,json=relPath,proto3" json:"rel_path,omitempty"`
	OpeLogEntries []*OpeLogEntry         `protobuf:"bytes,2,rep,name=ope_log_entries,json=opeLogEntries,proto3" json:"ope_log_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_grpc_opelog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetRelPath() string {
	if x != nil {
		return x.RelPath
	}
	return ""
}

func (x *LogEntry) GetOpeLogEntries() []*OpeLogEntry {
	if x != nil {
		return x.OpeLogEntries
	}
	return nil
}

type StoredEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                  `protobuf:"varint,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	SymLinkTarget string                 `protobuf:"bytes,6,opt,name=sym_link_target,json=symLinkTarget,proto3" json:"sym_link_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredEntry) Reset() {
	*x = StoredEntry{}
	mi := &file_grpc_opelog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredEntry) ProtoMessage() {}

func (x *StoredEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredEntry.ProtoReflect.Descriptor instead.
func (*StoredEntry) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{1}
}

func (x *StoredEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StoredEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *StoredEntry) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *StoredEntry) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *StoredEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StoredEntry) GetSymLinkTarget() string {
	if x != nil {
		return x.SymLinkTarget
	}
	return ""
}

type OpeLogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Code      OpeCode                `protobuf:"varint,1,opt,name=code,proto3,enum=opelog.OpeCode" json:"code,omitempty"`
	Check     bool                   `protobuf:"varint,2,opt,name=check,proto3" json:"check,omitempty"`
	TimeStamp int64                  `protobuf:"varint,3,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	ErrorId   uint64                 `protobuf:"varint,4,opt,name=error_id,json=errorId,proto3" json:"error_id,omitempty"`
	Source    *StoredEntry           `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Target    *StoredEntry           `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	// comma-separated list algo:hexa-of-checksum
	SourceChecksums string `protobuf:"bytes,7,opt,name=source_checksums,json=sourceChecksums,proto3" json:"source_checksums,omitempty"`
	TargetChecksums string `protobuf:"bytes,8,opt,name=target_checksums,json=targetChecksums,proto3" json:"target_checksums,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpeLogEntry) Reset() {
	*x = OpeLogEntry{}
	mi := &file_grpc_opelog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeLogEntry) ProtoMessage() {}

func (x *OpeLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeLogEntry.ProtoReflect.Descriptor instead.
func (*OpeLogEntry) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{2}
}

func (x *OpeLogEntry) GetCode() OpeCode {
	if x != nil {
		return x.Code
	}
	return OpeCode_OPE_CODE_UNSPECIFIED
}

func (x *OpeLogEntry) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *OpeLogEntry) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *OpeLogEntry) GetErrorId() uint64 {
	if x != nil {
		return x.ErrorId
	}
	return 0
}

func (x *OpeLogEntry) GetSource() *StoredEntry {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *OpeLogEntry) GetTarget() *StoredEntry {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *OpeLogEntry) GetSourceChecksums() string {
	if x != nil {
		return x.SourceChecksums
	}
	return ""
}

func (x *OpeLogEntry) GetTargetChecksums() string {
	if x != nil {
		return x.TargetChecksums
	}
	return ""
}

// For a memory to file simple implementation, limited to 2GiB, cf https://protobuf.dev/programming-guides/proto-limits/#total
type OpeLogAllInOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	LogEntries    []*LogEntry            `protobuf:"bytes,3,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeLogAllInOne) Reset() {
	*x = OpeLogAllInOne{}
	mi := &file_grpc_opelog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeLogAllInOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeLogAllInOne) ProtoMessage() {}

func (x *OpeLogAllInOne) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeLogAllInOne.ProtoReflect.Descriptor instead.
func (*OpeLogAllInOne) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{3}
}

func (x *OpeLogAllInOne) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OpeLogAllInOne) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *OpeLogAllInOne) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

var File_grpc_opelog_proto protoreflect.FileDescriptor

const file_grpc_opelog_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/opelog.proto\x12\x06opelog\"b\n" +
	"\bLogEntry\x12\x19\n" +
	"\brel_path\x18\x01 \x01(\tR\arelPath\x12;\n" +
	"\x0fope_log_entries\x18\x02 \x03(\v2\x13.opelog.OpeLogEntryR\ropeLogEntries\"\x97\x01\n" +
	"\vStoredEntry\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x02 \x01(\x03R\x05mtime\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12&\n" +
	"\x0fsym_link_target\x18\x06 \x01(\tR\rsymLinkTarget\"\xb2\x02\n" +
	"\vOpeLogEntry\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.opelog.OpeCodeR\x04code\x12\x14\n" +
	"\x05check\x18\x02 \x01(\bR\x05check\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x03 \x01(\x03R\ttimeStamp\x12\x19\n" +
	"\berror_id\x18\x04 \x01(\x04R\aerrorId\x12+\n" +
	"\x06source\x18\x05 \x01(\v2\x13.opelog.StoredEntryR\x06source\x12+\n" +
	"\x06target\x18\x06 \x01(\v2\x13.opelog.StoredEntryR\x06target\x12)\n" +
	"\x10source_checksums\x18\a \x01(\tR\x0fsourceChecksums\x12)\n" +
	"\x10target_checksums\x18\b \x01(\tR\x0ftargetChecksums\"s\n" +
	"\x0eOpeLogAllInOne\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x121\n" +
	"\vlog_entries\x18\x03 \x03(\v2\x10.opelog.LogEntryR\n" +
	"logEntries*\xfc\x01\n" +
	"\aOpeCode\x12\x18\n" +
	"\x14OPE_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OPE_CODE_SOURCE_STAT\x10\x01\x12\x18\n" +
	"\x14OPE_CODE_TARGET_STAT\x10\x02\x12\x1c\n" +
	"\x18OPE_CODE_SOURCE_CHECKSUM\x10\x03\x12\x1c\n" +
	"\x18OPE_CODE_TARGET_CHECKSUM\x10\x04\x12\x12\n" +
	"\x0eOPE_CODE_MKDIR\x10\x05\x12\x11\n" +
	"\rOPE_CODE_COPY\x10\x06\x12\x14\n" +
	"\x10OPE_CODE_SYMLINK\x10\a\x12\x13\n" +
	"\x0fOPE_CODE_DELETE\x10\b\x12\x15\n" +
	"\x11OPE_CODE_SET_STAT\x10\tB\x0eZ\f./opeloggrpcb\x06proto3"

var (
	file_grpc_opelog_proto_rawDescOnce sync.Once
	file_grpc_opelog_proto_rawDescData []byte
)

func file_grpc_opelog_proto_rawDescGZIP() []byte {
	file_grpc_opelog_proto_rawDescOnce.Do(func() {
		file_grpc_opelog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_opelog_proto_rawDesc), len(file_grpc_opelog_proto_rawDesc)))
	})
	return file_grpc_opelog_proto_rawDescData
}

var file_grpc_opelog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_opelog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_opelog_proto_goTypes = []any{
	(OpeCode)(0),           // 0: opelog.OpeCode
	(*LogEntry)(nil),       // 1: opelog.LogEntry
	(*StoredEntry)(nil),    // 2: opelog.StoredEntry
	(*OpeLogEntry)(nil),    // 3: opelog.OpeLogEntry
	(*OpeLogAllInOne)(nil), // 4: opelog.OpeLogAllInOne
}
var file_grpc_opelog_proto_depIdxs = []int32{
	3, // 0: opelog.LogEntry.ope_log_entries:type_name -> opelog.OpeLogEntry
	0, // 1: opelog.OpeLogEntry.code:type_name -> opelog.OpeCode
	2, // 2: opelog.OpeLogEntry.source:type_name -> opelog.StoredEntry
	2, // 3: opelog.OpeLogEntry.target:type_name -> opelog.StoredEntry
	1, // 4: opelog.OpeLogAllInOne.log_entries:type_name -> opelog.LogEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grpc_opelog_proto_init() }
func file_grpc_opelog_proto_init() {
	if File_grpc_opelog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_opelog_proto_rawDesc), len(file_grpc_opelog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_opelog_proto_goTypes,
		DependencyIndexes: file_grpc_opelog_proto_depIdxs,
		EnumInfos:         file_grpc_opelog_proto_enumTypes,
		MessageInfos:      file_grpc_opelog_proto_msgTypes,
	}.Build()
	File_grpc_opelog_proto = out.File
	file_grpc_opelog_proto_goTypes = nil
	file_grpc_opelog_proto_depIdxs = nil
}
