// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: grpc/opelog.proto

package opeloggrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HalgoCode int32

const (
	HalgoCode_HAL_UNSPECIFIED HalgoCode = 0
	HalgoCode_HAL_MD5         HalgoCode = 1
	HalgoCode_HAL_SHA256      HalgoCode = 2
	HalgoCode_HAL_SHA512      HalgoCode = 3
	HalgoCode_HAL_SHA3_256    HalgoCode = 4
	HalgoCode_HAL_SHA3_512    HalgoCode = 5
)

// Enum value maps for HalgoCode.
var (
	HalgoCode_name = map[int32]string{
		0: "HAL_UNSPECIFIED",
		1: "HAL_MD5",
		2: "HAL_SHA256",
		3: "HAL_SHA512",
		4: "HAL_SHA3_256",
		5: "HAL_SHA3_512",
	}
	HalgoCode_value = map[string]int32{
		"HAL_UNSPECIFIED": 0,
		"HAL_MD5":         1,
		"HAL_SHA256":      2,
		"HAL_SHA512":      3,
		"HAL_SHA3_256":    4,
		"HAL_SHA3_512":    5,
	}
)

func (x HalgoCode) Enum() *HalgoCode {
	p := new(HalgoCode)
	*p = x
	return p
}

func (x HalgoCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HalgoCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_opelog_proto_enumTypes[0].Descriptor()
}

func (HalgoCode) Type() protoreflect.EnumType {
	return &file_grpc_opelog_proto_enumTypes[0]
}

func (x HalgoCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HalgoCode.Descriptor instead.
func (HalgoCode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{0}
}

type EventCode int32

const (
	EventCode_EVC_UNSPECIFIED  EventCode = 0
	EventCode_EVC_LOADED       EventCode = 1
	EventCode_EVC_REMOVED      EventCode = 2
	EventCode_EVC_CREATED      EventCode = 3
	EventCode_EVC_UPDATED      EventCode = 4
	EventCode_EVC_META_CHANGED EventCode = 5
)

// Enum value maps for EventCode.
var (
	EventCode_name = map[int32]string{
		0: "EVC_UNSPECIFIED",
		1: "EVC_LOADED",
		2: "EVC_REMOVED",
		3: "EVC_CREATED",
		4: "EVC_UPDATED",
		5: "EVC_META_CHANGED",
	}
	EventCode_value = map[string]int32{
		"EVC_UNSPECIFIED":  0,
		"EVC_LOADED":       1,
		"EVC_REMOVED":      2,
		"EVC_CREATED":      3,
		"EVC_UPDATED":      4,
		"EVC_META_CHANGED": 5,
	}
)

func (x EventCode) Enum() *EventCode {
	p := new(EventCode)
	*p = x
	return p
}

func (x EventCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_opelog_proto_enumTypes[1].Descriptor()
}

func (EventCode) Type() protoreflect.EnumType {
	return &file_grpc_opelog_proto_enumTypes[1]
}

func (x EventCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventCode.Descriptor instead.
func (EventCode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{1}
}

type StateCode int32

const (
	StateCode_STC_UNSPECIFIED  StateCode = 0
	StateCode_STC_DONE_ABSENT  StateCode = 1
	StateCode_STC_DONE_PRESENT StateCode = 2
	StateCode_STC_DIR_LOAD     StateCode = 3
	StateCode_STC_DIR_RM       StateCode = 4
	StateCode_STC_DIR_CHANGE   StateCode = 5
	StateCode_STC_SE_ERROR     StateCode = 6
	// error from descendants are propagated, loading is partial, modification is blocked
	// redo will retry required actions
	StateCode_STC_DESC_ERROR StateCode = 7
)

// Enum value maps for StateCode.
var (
	StateCode_name = map[int32]string{
		0: "STC_UNSPECIFIED",
		1: "STC_DONE_ABSENT",
		2: "STC_DONE_PRESENT",
		3: "STC_DIR_LOAD",
		4: "STC_DIR_RM",
		5: "STC_DIR_CHANGE",
		6: "STC_SE_ERROR",
		7: "STC_DESC_ERROR",
	}
	StateCode_value = map[string]int32{
		"STC_UNSPECIFIED":  0,
		"STC_DONE_ABSENT":  1,
		"STC_DONE_PRESENT": 2,
		"STC_DIR_LOAD":     3,
		"STC_DIR_RM":       4,
		"STC_DIR_CHANGE":   5,
		"STC_SE_ERROR":     6,
		"STC_DESC_ERROR":   7,
	}
)

func (x StateCode) Enum() *StateCode {
	p := new(StateCode)
	*p = x
	return p
}

func (x StateCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_opelog_proto_enumTypes[2].Descriptor()
}

func (StateCode) Type() protoreflect.EnumType {
	return &file_grpc_opelog_proto_enumTypes[2]
}

func (x StateCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateCode.Descriptor instead.
func (StateCode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{2}
}

type Rights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          bool                   `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write         bool                   `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	Execute       bool                   `protobuf:"varint,3,opt,name=execute,proto3" json:"execute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rights) Reset() {
	*x = Rights{}
	mi := &file_grpc_opelog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rights) ProtoMessage() {}

func (x *Rights) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rights.ProtoReflect.Descriptor instead.
func (*Rights) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{0}
}

func (x *Rights) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Rights) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

func (x *Rights) GetExecute() bool {
	if x != nil {
		return x.Execute
	}
	return false
}

type StoredEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDir         bool                   `protobuf:"varint,1,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                  `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	User          int32                  `protobuf:"varint,4,opt,name=user,proto3" json:"user,omitempty"`
	UserRights    *Rights                `protobuf:"bytes,5,opt,name=user_rights,json=userRights,proto3" json:"user_rights,omitempty"`
	Group         int32                  `protobuf:"varint,6,opt,name=group,proto3" json:"group,omitempty"`
	GroupRights   *Rights                `protobuf:"bytes,7,opt,name=group_rights,json=groupRights,proto3" json:"group_rights,omitempty"`
	OtherRights   *Rights                `protobuf:"bytes,8,opt,name=other_rights,json=otherRights,proto3" json:"other_rights,omitempty"`
	IsSymLink     bool                   `protobuf:"varint,9,opt,name=is_sym_link,json=isSymLink,proto3" json:"is_sym_link,omitempty"`
	SymLinkTarget string                 `protobuf:"bytes,10,opt,name=sym_link_target,json=symLinkTarget,proto3" json:"sym_link_target,omitempty"`
	Children      []string               `protobuf:"bytes,11,rep,name=children,proto3" json:"children,omitempty"`
	AddMeta       []byte                 `protobuf:"bytes,12,opt,name=add_meta,json=addMeta,proto3" json:"add_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredEntry) Reset() {
	*x = StoredEntry{}
	mi := &file_grpc_opelog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredEntry) ProtoMessage() {}

func (x *StoredEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredEntry.ProtoReflect.Descriptor instead.
func (*StoredEntry) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{1}
}

func (x *StoredEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StoredEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StoredEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *StoredEntry) GetUser() int32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *StoredEntry) GetUserRights() *Rights {
	if x != nil {
		return x.UserRights
	}
	return nil
}

func (x *StoredEntry) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *StoredEntry) GetGroupRights() *Rights {
	if x != nil {
		return x.GroupRights
	}
	return nil
}

func (x *StoredEntry) GetOtherRights() *Rights {
	if x != nil {
		return x.OtherRights
	}
	return nil
}

func (x *StoredEntry) GetIsSymLink() bool {
	if x != nil {
		return x.IsSymLink
	}
	return false
}

func (x *StoredEntry) GetSymLinkTarget() string {
	if x != nil {
		return x.SymLinkTarget
	}
	return ""
}

func (x *StoredEntry) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *StoredEntry) GetAddMeta() []byte {
	if x != nil {
		return x.AddMeta
	}
	return nil
}

type TypedChecksum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// first byte is HalgoCode, checksum comes after
	Tcs           []byte `protobuf:"bytes,1,opt,name=tcs,proto3" json:"tcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedChecksum) Reset() {
	*x = TypedChecksum{}
	mi := &file_grpc_opelog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedChecksum) ProtoMessage() {}

func (x *TypedChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedChecksum.ProtoReflect.Descriptor instead.
func (*TypedChecksum) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{2}
}

func (x *TypedChecksum) GetTcs() []byte {
	if x != nil {
		return x.Tcs
	}
	return nil
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	IsTarget  bool                   `protobuf:"varint,1,opt,name=is_target,json=isTarget,proto3" json:"is_target,omitempty"`
	Kind      EventCode              `protobuf:"varint,2,opt,name=kind,proto3,enum=opelog.EventCode" json:"kind,omitempty"`
	TimeStamp int64                  `protobuf:"varint,3,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	// values shared by index, negative index means no value
	SeNum         int32   `protobuf:"zigzag32,4,opt,name=se_num,json=seNum,proto3" json:"se_num,omitempty"`
	TcsNums       []int32 `protobuf:"zigzag32,5,rep,packed,name=tcs_nums,json=tcsNums,proto3" json:"tcs_nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_grpc_opelog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetIsTarget() bool {
	if x != nil {
		return x.IsTarget
	}
	return false
}

func (x *Event) GetKind() EventCode {
	if x != nil {
		return x.Kind
	}
	return EventCode_EVC_UNSPECIFIED
}

func (x *Event) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *Event) GetSeNum() int32 {
	if x != nil {
		return x.SeNum
	}
	return 0
}

func (x *Event) GetTcsNums() []int32 {
	if x != nil {
		return x.TcsNums
	}
	return nil
}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventsList    []*Event               `protobuf:"bytes,1,rep,name=events_list,json=eventsList,proto3" json:"events_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_grpc_opelog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{4}
}

func (x *Events) GetEventsList() []*Event {
	if x != nil {
		return x.EventsList
	}
	return nil
}

type AggInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggInfo) Reset() {
	*x = AggInfo{}
	mi := &file_grpc_opelog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggInfo) ProtoMessage() {}

func (x *AggInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggInfo.ProtoReflect.Descriptor instead.
func (*AggInfo) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{5}
}

func (x *AggInfo) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *AggInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ComputedStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list for dirs, stats for others, performed both on source and target
	SourceListOrStat *AggInfo `protobuf:"bytes,1,opt,name=source_list_or_stat,json=sourceListOrStat,proto3" json:"source_list_or_stat,omitempty"`
	TargetListOrStat *AggInfo `protobuf:"bytes,2,opt,name=target_list_or_stat,json=targetListOrStat,proto3" json:"target_list_or_stat,omitempty"`
	// other I/Os specific to source or to target
	Read          *AggInfo `protobuf:"bytes,3,opt,name=read,proto3" json:"read,omitempty"`
	Create        *AggInfo `protobuf:"bytes,4,opt,name=create,proto3" json:"create,omitempty"`
	Update        *AggInfo `protobuf:"bytes,5,opt,name=update,proto3" json:"update,omitempty"`
	Remove        *AggInfo `protobuf:"bytes,6,opt,name=remove,proto3" json:"remove,omitempty"`
	MetaChange    *AggInfo `protobuf:"bytes,7,opt,name=meta_change,json=metaChange,proto3" json:"meta_change,omitempty"`
	Error         *AggInfo `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputedStats) Reset() {
	*x = ComputedStats{}
	mi := &file_grpc_opelog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputedStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputedStats) ProtoMessage() {}

func (x *ComputedStats) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputedStats.ProtoReflect.Descriptor instead.
func (*ComputedStats) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{6}
}

func (x *ComputedStats) GetSourceListOrStat() *AggInfo {
	if x != nil {
		return x.SourceListOrStat
	}
	return nil
}

func (x *ComputedStats) GetTargetListOrStat() *AggInfo {
	if x != nil {
		return x.TargetListOrStat
	}
	return nil
}

func (x *ComputedStats) GetRead() *AggInfo {
	if x != nil {
		return x.Read
	}
	return nil
}

func (x *ComputedStats) GetCreate() *AggInfo {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *ComputedStats) GetUpdate() *AggInfo {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ComputedStats) GetRemove() *AggInfo {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *ComputedStats) GetMetaChange() *AggInfo {
	if x != nil {
		return x.MetaChange
	}
	return nil
}

func (x *ComputedStats) GetError() *AggInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

type State struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	IsTarget bool                   `protobuf:"varint,1,opt,name=is_target,json=isTarget,proto3" json:"is_target,omitempty"`
	Stc      StateCode              `protobuf:"varint,2,opt,name=stc,proto3,enum=opelog.StateCode" json:"stc,omitempty"`
	// values shared by index, negative index means no value
	SeNum         int32   `protobuf:"zigzag32,3,opt,name=se_num,json=seNum,proto3" json:"se_num,omitempty"`
	TcsNums       []int32 `protobuf:"zigzag32,4,rep,packed,name=tcs_nums,json=tcsNums,proto3" json:"tcs_nums,omitempty"`
	DepCount      int32   `protobuf:"varint,5,opt,name=dep_count,json=depCount,proto3" json:"dep_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_grpc_opelog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{7}
}

func (x *State) GetIsTarget() bool {
	if x != nil {
		return x.IsTarget
	}
	return false
}

func (x *State) GetStc() StateCode {
	if x != nil {
		return x.Stc
	}
	return StateCode_STC_UNSPECIFIED
}

func (x *State) GetSeNum() int32 {
	if x != nil {
		return x.SeNum
	}
	return 0
}

func (x *State) GetTcsNums() []int32 {
	if x != nil {
		return x.TcsNums
	}
	return nil
}

func (x *State) GetDepCount() int32 {
	if x != nil {
		return x.DepCount
	}
	return 0
}

type LogicalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Checksums and stored entries are shared and referenced by index
	SharedSes  []*StoredEntry   `protobuf:"bytes,1,rep,name=shared_ses,json=sharedSes,proto3" json:"shared_ses,omitempty"`
	SharedTcss []*TypedChecksum `protobuf:"bytes,2,rep,name=shared_tcss,json=sharedTcss,proto3" json:"shared_tcss,omitempty"`
	// states relate to one session or to one inventory
	SourceStates map[int64]*State `protobuf:"bytes,3,rep,name=source_states,json=sourceStates,proto3" json:"source_states,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TargetStates map[int64]*State `protobuf:"bytes,4,rep,name=target_states,json=targetStates,proto3" json:"target_states,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// events relate to one session
	EventsLists map[int64]*Events `protobuf:"bytes,5,rep,name=eventsLists,proto3" json:"eventsLists,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// stats relate to one session
	Stats         map[int64]*ComputedStats `protobuf:"bytes,6,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalEntry) Reset() {
	*x = LogicalEntry{}
	mi := &file_grpc_opelog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalEntry) ProtoMessage() {}

func (x *LogicalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalEntry.ProtoReflect.Descriptor instead.
func (*LogicalEntry) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{8}
}

func (x *LogicalEntry) GetSharedSes() []*StoredEntry {
	if x != nil {
		return x.SharedSes
	}
	return nil
}

func (x *LogicalEntry) GetSharedTcss() []*TypedChecksum {
	if x != nil {
		return x.SharedTcss
	}
	return nil
}

func (x *LogicalEntry) GetSourceStates() map[int64]*State {
	if x != nil {
		return x.SourceStates
	}
	return nil
}

func (x *LogicalEntry) GetTargetStates() map[int64]*State {
	if x != nil {
		return x.TargetStates
	}
	return nil
}

func (x *LogicalEntry) GetEventsLists() map[int64]*Events {
	if x != nil {
		return x.EventsLists
	}
	return nil
}

func (x *LogicalEntry) GetStats() map[int64]*ComputedStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// For a memory to file simple implementation, limited to 2GiB, cf https://protobuf.dev/programming-guides/proto-limits/#total
type OpeLogAllInOne struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceRoot string                 `protobuf:"bytes,1,opt,name=source_root,json=sourceRoot,proto3" json:"source_root,omitempty"`
	TargetRoot string                 `protobuf:"bytes,2,opt,name=target_root,json=targetRoot,proto3" json:"target_root,omitempty"`
	// the key is the relative path
	LogicalEntries map[string]*LogicalEntry `protobuf:"bytes,3,rep,name=logical_entries,json=logicalEntries,proto3" json:"logical_entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// the key is the session label the value is its unique reference time
	Sessions map[string]int64 `protobuf:"bytes,4,rep,name=sessions,proto3" json:"sessions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// the key is the inventory label the value is its unique reference time
	Inventories   map[string]int64 `protobuf:"bytes,5,rep,name=inventories,proto3" json:"inventories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeLogAllInOne) Reset() {
	*x = OpeLogAllInOne{}
	mi := &file_grpc_opelog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeLogAllInOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeLogAllInOne) ProtoMessage() {}

func (x *OpeLogAllInOne) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_opelog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeLogAllInOne.ProtoReflect.Descriptor instead.
func (*OpeLogAllInOne) Descriptor() ([]byte, []int) {
	return file_grpc_opelog_proto_rawDescGZIP(), []int{9}
}

func (x *OpeLogAllInOne) GetSourceRoot() string {
	if x != nil {
		return x.SourceRoot
	}
	return ""
}

func (x *OpeLogAllInOne) GetTargetRoot() string {
	if x != nil {
		return x.TargetRoot
	}
	return ""
}

func (x *OpeLogAllInOne) GetLogicalEntries() map[string]*LogicalEntry {
	if x != nil {
		return x.LogicalEntries
	}
	return nil
}

func (x *OpeLogAllInOne) GetSessions() map[string]int64 {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *OpeLogAllInOne) GetInventories() map[string]int64 {
	if x != nil {
		return x.Inventories
	}
	return nil
}

var File_grpc_opelog_proto protoreflect.FileDescriptor

const file_grpc_opelog_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/opelog.proto\x12\x06opelog\"L\n" +
	"\x06Rights\x12\x12\n" +
	"\x04read\x18\x01 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x02 \x01(\bR\x05write\x12\x18\n" +
	"\aexecute\x18\x03 \x01(\bR\aexecute\"\x8e\x03\n" +
	"\vStoredEntry\x12\x15\n" +
	"\x06is_dir\x18\x01 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x03 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04user\x18\x04 \x01(\x05R\x04user\x12/\n" +
	"\vuser_rights\x18\x05 \x01(\v2\x0e.opelog.RightsR\n" +
	"userRights\x12\x14\n" +
	"\x05group\x18\x06 \x01(\x05R\x05group\x121\n" +
	"\fgroup_rights\x18\a \x01(\v2\x0e.opelog.RightsR\vgroupRights\x121\n" +
	"\fother_rights\x18\b \x01(\v2\x0e.opelog.RightsR\votherRights\x12\x1e\n" +
	"\vis_sym_link\x18\t \x01(\bR\tisSymLink\x12&\n" +
	"\x0fsym_link_target\x18\n" +
	" \x01(\tR\rsymLinkTarget\x12\x1a\n" +
	"\bchildren\x18\v \x03(\tR\bchildren\x12\x19\n" +
	"\badd_meta\x18\f \x01(\fR\aaddMeta\"!\n" +
	"\rTypedChecksum\x12\x10\n" +
	"\x03tcs\x18\x01 \x01(\fR\x03tcs\"\x9c\x01\n" +
	"\x05Event\x12\x1b\n" +
	"\tis_target\x18\x01 \x01(\bR\bisTarget\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.opelog.EventCodeR\x04kind\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x03 \x01(\x03R\ttimeStamp\x12\x15\n" +
	"\x06se_num\x18\x04 \x01(\x11R\x05seNum\x12\x19\n" +
	"\btcs_nums\x18\x05 \x03(\x11R\atcsNums\"8\n" +
	"\x06Events\x12.\n" +
	"\vevents_list\x18\x01 \x03(\v2\r.opelog.EventR\n" +
	"eventsList\"5\n" +
	"\aAggInfo\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\x88\x03\n" +
	"\rComputedStats\x12>\n" +
	"\x13source_list_or_stat\x18\x01 \x01(\v2\x0f.opelog.AggInfoR\x10sourceListOrStat\x12>\n" +
	"\x13target_list_or_stat\x18\x02 \x01(\v2\x0f.opelog.AggInfoR\x10targetListOrStat\x12#\n" +
	"\x04read\x18\x03 \x01(\v2\x0f.opelog.AggInfoR\x04read\x12'\n" +
	"\x06create\x18\x04 \x01(\v2\x0f.opelog.AggInfoR\x06create\x12'\n" +
	"\x06update\x18\x05 \x01(\v2\x0f.opelog.AggInfoR\x06update\x12'\n" +
	"\x06remove\x18\x06 \x01(\v2\x0f.opelog.AggInfoR\x06remove\x120\n" +
	"\vmeta_change\x18\a \x01(\v2\x0f.opelog.AggInfoR\n" +
	"metaChange\x12%\n" +
	"\x05error\x18\b \x01(\v2\x0f.opelog.AggInfoR\x05error\"\x98\x01\n" +
	"\x05State\x12\x1b\n" +
	"\tis_target\x18\x01 \x01(\bR\bisTarget\x12#\n" +
	"\x03stc\x18\x02 \x01(\x0e2\x11.opelog.StateCodeR\x03stc\x12\x15\n" +
	"\x06se_num\x18\x03 \x01(\x11R\x05seNum\x12\x19\n" +
	"\btcs_nums\x18\x04 \x03(\x11R\atcsNums\x12\x1b\n" +
	"\tdep_count\x18\x05 \x01(\x05R\bdepCount\"\xd5\x05\n" +
	"\fLogicalEntry\x122\n" +
	"\n" +
	"shared_ses\x18\x01 \x03(\v2\x13.opelog.StoredEntryR\tsharedSes\x126\n" +
	"\vshared_tcss\x18\x02 \x03(\v2\x15.opelog.TypedChecksumR\n" +
	"sharedTcss\x12K\n" +
	"\rsource_states\x18\x03 \x03(\v2&.opelog.LogicalEntry.SourceStatesEntryR\fsourceStates\x12K\n" +
	"\rtarget_states\x18\x04 \x03(\v2&.opelog.LogicalEntry.TargetStatesEntryR\ftargetStates\x12G\n" +
	"\veventsLists\x18\x05 \x03(\v2%.opelog.LogicalEntry.EventsListsEntryR\veventsLists\x125\n" +
	"\x05stats\x18\x06 \x03(\v2\x1f.opelog.LogicalEntry.StatsEntryR\x05stats\x1aN\n" +
	"\x11SourceStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.opelog.StateR\x05value:\x028\x01\x1aN\n" +
	"\x11TargetStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.opelog.StateR\x05value:\x028\x01\x1aN\n" +
	"\x10EventsListsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.opelog.EventsR\x05value:\x028\x01\x1aO\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.opelog.ComputedStatsR\x05value:\x028\x01\"\x8a\x04\n" +
	"\x0eOpeLogAllInOne\x12\x1f\n" +
	"\vsource_root\x18\x01 \x01(\tR\n" +
	"sourceRoot\x12\x1f\n" +
	"\vtarget_root\x18\x02 \x01(\tR\n" +
	"targetRoot\x12S\n" +
	"\x0flogical_entries\x18\x03 \x03(\v2*.opelog.OpeLogAllInOne.LogicalEntriesEntryR\x0elogicalEntries\x12@\n" +
	"\bsessions\x18\x04 \x03(\v2$.opelog.OpeLogAllInOne.SessionsEntryR\bsessions\x12I\n" +
	"\vinventories\x18\x05 \x03(\v2'.opelog.OpeLogAllInOne.InventoriesEntryR\vinventories\x1aW\n" +
	"\x13LogicalEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.opelog.LogicalEntryR\x05value:\x028\x01\x1a;\n" +
	"\rSessionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10InventoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*q\n" +
	"\tHalgoCode\x12\x13\n" +
	"\x0fHAL_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aHAL_MD5\x10\x01\x12\x0e\n" +
	"\n" +
	"HAL_SHA256\x10\x02\x12\x0e\n" +
	"\n" +
	"HAL_SHA512\x10\x03\x12\x10\n" +
	"\fHAL_SHA3_256\x10\x04\x12\x10\n" +
	"\fHAL_SHA3_512\x10\x05*y\n" +
	"\tEventCode\x12\x13\n" +
	"\x0fEVC_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"EVC_LOADED\x10\x01\x12\x0f\n" +
	"\vEVC_REMOVED\x10\x02\x12\x0f\n" +
	"\vEVC_CREATED\x10\x03\x12\x0f\n" +
	"\vEVC_UPDATED\x10\x04\x12\x14\n" +
	"\x10EVC_META_CHANGED\x10\x05*\xa7\x01\n" +
	"\tStateCode\x12\x13\n" +
	"\x0fSTC_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTC_DONE_ABSENT\x10\x01\x12\x14\n" +
	"\x10STC_DONE_PRESENT\x10\x02\x12\x10\n" +
	"\fSTC_DIR_LOAD\x10\x03\x12\x0e\n" +
	"\n" +
	"STC_DIR_RM\x10\x04\x12\x12\n" +
	"\x0eSTC_DIR_CHANGE\x10\x05\x12\x10\n" +
	"\fSTC_SE_ERROR\x10\x06\x12\x12\n" +
	"\x0eSTC_DESC_ERROR\x10\aB\x0eZ\f./opeloggrpcb\x06proto3"

var (
	file_grpc_opelog_proto_rawDescOnce sync.Once
	file_grpc_opelog_proto_rawDescData []byte
)

func file_grpc_opelog_proto_rawDescGZIP() []byte {
	file_grpc_opelog_proto_rawDescOnce.Do(func() {
		file_grpc_opelog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_opelog_proto_rawDesc), len(file_grpc_opelog_proto_rawDesc)))
	})
	return file_grpc_opelog_proto_rawDescData
}

var file_grpc_opelog_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpc_opelog_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_grpc_opelog_proto_goTypes = []any{
	(HalgoCode)(0),         // 0: opelog.HalgoCode
	(EventCode)(0),         // 1: opelog.EventCode
	(StateCode)(0),         // 2: opelog.StateCode
	(*Rights)(nil),         // 3: opelog.Rights
	(*StoredEntry)(nil),    // 4: opelog.StoredEntry
	(*TypedChecksum)(nil),  // 5: opelog.TypedChecksum
	(*Event)(nil),          // 6: opelog.Event
	(*Events)(nil),         // 7: opelog.Events
	(*AggInfo)(nil),        // 8: opelog.AggInfo
	(*ComputedStats)(nil),  // 9: opelog.ComputedStats
	(*State)(nil),          // 10: opelog.State
	(*LogicalEntry)(nil),   // 11: opelog.LogicalEntry
	(*OpeLogAllInOne)(nil), // 12: opelog.OpeLogAllInOne
	nil,                    // 13: opelog.LogicalEntry.SourceStatesEntry
	nil,                    // 14: opelog.LogicalEntry.TargetStatesEntry
	nil,                    // 15: opelog.LogicalEntry.EventsListsEntry
	nil,                    // 16: opelog.LogicalEntry.StatsEntry
	nil,                    // 17: opelog.OpeLogAllInOne.LogicalEntriesEntry
	nil,                    // 18: opelog.OpeLogAllInOne.SessionsEntry
	nil,                    // 19: opelog.OpeLogAllInOne.InventoriesEntry
}
var file_grpc_opelog_proto_depIdxs = []int32{
	3,  // 0: opelog.StoredEntry.user_rights:type_name -> opelog.Rights
	3,  // 1: opelog.StoredEntry.group_rights:type_name -> opelog.Rights
	3,  // 2: opelog.StoredEntry.other_rights:type_name -> opelog.Rights
	1,  // 3: opelog.Event.kind:type_name -> opelog.EventCode
	6,  // 4: opelog.Events.events_list:type_name -> opelog.Event
	8,  // 5: opelog.ComputedStats.source_list_or_stat:type_name -> opelog.AggInfo
	8,  // 6: opelog.ComputedStats.target_list_or_stat:type_name -> opelog.AggInfo
	8,  // 7: opelog.ComputedStats.read:type_name -> opelog.AggInfo
	8,  // 8: opelog.ComputedStats.create:type_name -> opelog.AggInfo
	8,  // 9: opelog.ComputedStats.update:type_name -> opelog.AggInfo
	8,  // 10: opelog.ComputedStats.remove:type_name -> opelog.AggInfo
	8,  // 11: opelog.ComputedStats.meta_change:type_name -> opelog.AggInfo
	8,  // 12: opelog.ComputedStats.error:type_name -> opelog.AggInfo
	2,  // 13: opelog.State.stc:type_name -> opelog.StateCode
	4,  // 14: opelog.LogicalEntry.shared_ses:type_name -> opelog.StoredEntry
	5,  // 15: opelog.LogicalEntry.shared_tcss:type_name -> opelog.TypedChecksum
	13, // 16: opelog.LogicalEntry.source_states:type_name -> opelog.LogicalEntry.SourceStatesEntry
	14, // 17: opelog.LogicalEntry.target_states:type_name -> opelog.LogicalEntry.TargetStatesEntry
	15, // 18: opelog.LogicalEntry.eventsLists:type_name -> opelog.LogicalEntry.EventsListsEntry
	16, // 19: opelog.LogicalEntry.stats:type_name -> opelog.LogicalEntry.StatsEntry
	17, // 20: opelog.OpeLogAllInOne.logical_entries:type_name -> opelog.OpeLogAllInOne.LogicalEntriesEntry
	18, // 21: opelog.OpeLogAllInOne.sessions:type_name -> opelog.OpeLogAllInOne.SessionsEntry
	19, // 22: opelog.OpeLogAllInOne.inventories:type_name -> opelog.OpeLogAllInOne.InventoriesEntry
	10, // 23: opelog.LogicalEntry.SourceStatesEntry.value:type_name -> opelog.State
	10, // 24: opelog.LogicalEntry.TargetStatesEntry.value:type_name -> opelog.State
	7,  // 25: opelog.LogicalEntry.EventsListsEntry.value:type_name -> opelog.Events
	9,  // 26: opelog.LogicalEntry.StatsEntry.value:type_name -> opelog.ComputedStats
	11, // 27: opelog.OpeLogAllInOne.LogicalEntriesEntry.value:type_name -> opelog.LogicalEntry
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_grpc_opelog_proto_init() }
func file_grpc_opelog_proto_init() {
	if File_grpc_opelog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_opelog_proto_rawDesc), len(file_grpc_opelog_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_opelog_proto_goTypes,
		DependencyIndexes: file_grpc_opelog_proto_depIdxs,
		EnumInfos:         file_grpc_opelog_proto_enumTypes,
		MessageInfos:      file_grpc_opelog_proto_msgTypes,
	}.Build()
	File_grpc_opelog_proto = out.File
	file_grpc_opelog_proto_goTypes = nil
	file_grpc_opelog_proto_depIdxs = nil
}
